baseurl = "http://bulkan-evcimen.com"
languageCode = "en-us"
title = "Bulkan Evcimen"
theme = "purehugo"
metaDataFormat = "yaml"
uglyURLs = true
paginate = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  disqusShortname = "bulkanevcimen"
  twitterName = "bulkanevcimen"
  githubName = "bulkan"
  google_analytics = "UA-1620638-6"
  description = "Software Engineer that plays the Ney"
